RevolutionPi/piControl

piControlMain.c
As a comment implies the author of the code did not see the requirement of
locking the copy of a byte value in case of the KB_GET_VALUE ioctl.
Unfortunately this assumption is wrong:
In case of two threads A (writer) and B (reader) that access the same data
we have to ensure memory coherency. Thus for thread A we must ensure that
the written value actually is written to its RAM destination and not held
in cache. For thread B we must ensure that the value is actually read from
RAM and not from cache. Since the spinlock lock()/unlock() operations imply
the required memory barriers both can be achieved by using spinlocks.
The writer already uses a spinlock to access the data. Use this for the
reader, too.
=> piControl: add missing lock

piControlMain.c
On the flat the module piControl depends on ad5446 which it uses for analog
output. However starting piControl on bootup may fail due to ad5446 not
being present at this time.
The reason is that there is that programs like modprobe do not know about
this module dependeny.
So give modprobe a hint by adding ad5446 to the list of modules specified
in MODULE_SOFTDEP.
Reported-by: Simon Han <z.han@kunbus.de>
=> piControl:flat: Specify module dependencies

RevPiDevice.c, piTest/piTest.c, revpi_flat.c
When the flat is reset setup the device information for the flat and all
further (virtual) devices.
This is needed for commands like piTest which want to display information
about present devices.
=> piControl:flat: Set device information at reset

debian/changelog
This release supports the KUNBUS RevPi Flat.
Signed-off-by: Philipp Rosenberger <p.rosenberger@kunbus.com>
=> piTest/debian: Create release 1.3.0-1~0flat1

revpi_flat.c
In revpi_flat_adjust_config() the list of devices that has been found by
parsing the configuration file is iterated.
However in case of an errorneous or not exising configuration file the
pointer that points to this list may be NULL.
Skip the device list iteration in this case to avoid a NULL pointer
dereference.
Reported-by: Simon Han <z.han@kunbus.de>
=> piControl:flat: check for valid cofniguration data

IoProtocol.h, Makefile, PiBridgeMaster.c, RevPiDevice.c, RevPiDevice.h, common_define.h, piConfig.c, piControl.h, piControlMain.c, piIOComm.c, piIOComm.h, revpi_mio.c, revpi_mio.h
Add the initial support for MultiIO module:
MultiIO module initialize
the analog output message is compressed
the calibration is supported
Signed-off-by: Zhi Han z.han@kunbus.com
=> piControl:flat: Add initial support for MultiIO module

piTest/piTest.c
the moduletype 118 has been used for the Multi IO in piControl,
piTest just follows that.
Signed-off-by: Zhi Han <z.han@kunbus.com>
=> piTest: add support for Multi IO

piConfig.c
When the file reading is finished, a log indicates the event. This
log should not be an error message.
And printing the mem address makes no sense here, and takes some
security risk.
Signed-off-by: Zhi Han <z.han@kunbus.com>
=> use pr_info to print a normal message in process_file

Makefile
I compile the kernel using a different compiler, with which I want to be able to compile piControl.
Changed the Makefile in such a way that I am able to influence the used compiler(toolchain).
=> Make CROSS_COMPILE make argument environment configurable instead of hardcoded

PiBridgeMaster.c
In PiBridgeMaster_setDefaults() dont use a INT8U variable to calculate the
offset of a bit within the shared memory segment (aka "process image").
This distorts all values which are greater than 255.
Instead use an unsigned int to provide the max possible offset within the
memory segment.
=> piControl: Dont use wrong offset for default values

revpi_gate.c
This reverts commit 66eb9fd3a11d.
Depends on https://github.com/RevolutionPi/linux/pull/49.
=> piControl: RevPi Gate communication with RT priority (REVPI-1740)

revpi_compact.c, revpi_flat.c
In case that the file config.rsc could not be read (e.g. since it does not
exist), the piDev_g.ent pointer which points to the settings extracted
from this file, is NULL. Since function revpi_set_defaults() is not
prepared for this situation it causes a NULL pointer access in this case.
Fix this by checking piDev_g.ent for NULL before calling
revpi_set_defaults().
=> piControl:flat: handle missing config settings [REVPI-1767]

revpi_compact.c, revpi_flat.c
In case that the file config.rsc could not be read (e.g. since it does not
exist), the piDev_g.ent pointer which points to the settings extracted
from this file, is NULL. Since function revpi_set_defaults() is not
prepared for this situation it causes a NULL pointer access in this case.
Fix this by checking piDev_g.ent for NULL before calling
revpi_set_defaults().
=> piControl:flat: handle missing config settings

revpi_compact.c
This reverts commit ff433a175f2288a99936729e459f30e2df10b8c5.
=> Revert "[HACK] Compact: Disable MAX31913 status"

piControlMain.c
Add a module dependency for the GPIO chip driver gpio-max3191x. This is
needed by REVPI compact to avoid situations in which piControl module is
loaded while the chip driver is not available yet.
=> piControl: add module depency for DIN on compact

piControlMain.c
Do not use combinations of access_ok() and __copy_from_user() or
__copy_to_user() as replacements for copy_from_user() and copy_to_user().
As pointed out by Lukas Wunner these functions do not perform all the
necessary checks needed to exchange data areas with userspace (see also
this comment of Linus Torvalds:
http://lkml.iu.edu/hypermail/linux/kernel/2007.3/06760.html).
So instead use copy_from_user() and copy_to_user().
Fixes: a5b39ae638fe ("piControl: Fix data copy for ioctl KB_GET_DEVICE_INFO")
Reported-by: Lukas Wunner <lukas@wunner.de>
=> piControl: use correct function to exchange data with userspace

RevPiDevice.c, RevPiDevice.h, piControlMain.c, revpi_core.c, revpi_gate.c
The receive handler for gateway packets, revpi_gate_rcv(), is called in
softirq context, hence cannot sleep.  However copying data to and from
the process image can only be performed from task context because
rt_mutexes may sleep.  Using a non-sleeping raw_spinlock_t for the
process image is not an option because user space access may sleep in
copy_from/to_user().  We could switch to the _nofault variant of
copy_from/to_user(), but that may break existing user space applications.
The best solution would be a reimplementation of the process image as a
lockless, RCU-protected scatterlist, but that's a complex undertaking.
As a bandaid, store received packets in a queue and defer processing
to a dedicated kthread running at RT priority.  This may slightly
increase latency for packet …
=> piControl: Process gateway packets in task context (REVPI-1797)

PiBridgeMaster.c, RevPiDevice.c, RevPiDevice.h, piAIOComm.c, piConfig.c, piControlMain.c, piDIOComm.c, piFirmwareUpdate.c, piIOComm.c, revpi_common.c, revpi_common.h, revpi_compact.c, revpi_core.c, revpi_core.h, revpi_flat.c, revpi_gate.c, revpi_mio.c
- remove fc3aea683927df3eb531acdde56eb6a98eddb484 ("Revert "[HACK] Compact: Disable MAX31913 status"")
- remove ff433a175f2288a99936729e459f30e2df10b8c5 ("[HACK] Compact: Disable MAX31913 status")
- remove 66eb9fd3a11d7cd4ae25821ea0f547a662d256a1 ("Gate: Set TC_PRIO_REALTIME only on kernel < 4.20")
- remove 88b61ddb2a2510cb399e6275ab0137c5ad3b7f6a ("fixup! Gate: Set TC_PRIO_REALTIME only on kernel < 4.20")
- remove 3e69a79628e91526dd80096dcf962e60fb21c22c ("[HACK] the access_ok macro has changed with 5.0.0")
- move c47048399e9c31bcfeb1b264e5ad4546a5cedc6f ("piControl: use correct function to exchange data with userspace")
- add 35a76e0e95839de2f2a9b380f02a114680de631d "(HEAD -> feature/REVPI-1833/cleanup, origin/feature/REVPI-1833/cleanup) piControl: compact: Replace …
=> Feature/revpi 1833/cleanup

process_image.h
The HRTIMER_MODE_ABS uses a softirq timer. This means the hrtimer will
wakup the softirqd and the softirqd will wakeup our thread. This causes
additional delays and jitter. We tried to combat this with increasing
the softirq priority.
The better solution is to wake our threads directly from hardware timer
interrupt. Thus using HRTIMER_MODE_ABS_HARD will do this for us.
Signed-off-by: Philipp Rosenberger <p.rosenberger@kunbus.com>
=> Use hardware interrupt timer instead in soft interrupt [REVPI-1936]

revpi_flat.c
We read the CPU temp. and freq. in the AIN thread. We acquire the lock
before we read the CPU temp. and freq. It is not needed to hold this
lock to do so. And as this might take a lot of time we might block the
DOUT thread.
Reading the CPU temp. and freq. outside the lock and hold the lock only
to write the values to the process image.
Signed-off-by: Philipp Rosenberger <p.rosenberger@kunbus.com>
=> flat: Shrink critical region in the ain thread [REVPI-1935]

revpi_flat.c
There was a bug inbtroduced with 1462519 ("flat: Shrink critical region
in the ain thread"). Check if ret is zero (no error) instead of
non-zero.
Also make the order in the comparrion explicit.
Signed-off-by: Philipp Rosenberger <p.rosenberger@kunbus.com>
=> flat: Fix bug introduced with 1462519 [REVPI-1935]

revpi_core.c
The gpio of x2do (relay) was erroneously assigned to x2di. As a result
neigher x2di nor x2do worked on RevPi Connect.
Fiixes 7877a9921cd2edaa04784b4bc86478b2c287b154
Signed-off-by: Nicolai Buchwitz <n.buchwitz@kunbus.com>
=> connect: Fix gpio assingment of x2do [REVPI-1949]

revpi_flat.c
ktimersoftd was removed with v5.0.19-rt11 patchset. Therefore manually setting
the rt prio of ktimersoftd results in an error on the RevPi Flat:
"piControl: cannot find kthread ktimersoftd/0"
Partialy revert of commit 370e4d9150ced81ed3dc61971a24a2f69744702d
Signed-off-by: Nicolai Buchwitz <n.buchwitz@kunbus.com>
=> Remove rt prio settings for ktimersoftd [REVPI-1964]

piControlMain.c
At module initialization the compatible string in the device tree is
checked to determine the device type. However there is no check for the
new compatible "kunbus,revpi-connect-se" yet, so that a Connect S is not
recognized as connect, but as a core (which is the default type).
Fix this by checking against the new compatible type.
=> piControl: support connect s compatible

PiBridgeMaster.c, RevPiDevice.c, piControlMain.c, piControlMain.h, piIOComm.c, revpi_core.c
following changes are made for Core SE and Connect SE:
1. add SE device to revpi_machine
2. set the machine_type in piControlInit()
3. check machine_type, if not SE call revpi_gate_init();
4. add code for Connect SE in every appearance of REVPI_CONNECT
5. add code for Core SE in every appearance of REVPI_CORE
=> add support for SE device (machine_type)

piAIOComm.c, piDIOComm.c, piIOComm.c, piIOComm.h, revpi_core.c, revpi_core.h
There is a serdev implementation for the RS485 piBridge-communication
available. Use that instead of establishing an own serial connection in
piControl. For now we only replace the low-level functions with
pibridge_send() and pibridge_recv_timeout() to keep code changes minimal.
An exception is the use of pibridge_req_gate_tmt() which covers a hole
transaction (request and reception of data with consecutive check of
received data; in a later step only high-level functions that cover
complete transactions should be used).
Clean up the code and remove everything that is not needed any longer,
especially the UART thread and the related data structures which are now
replaced by the functionality implemented in the serdev module.
=> piControl: use serdev based revpi-comm device for RS485 communication

PiBridgeMaster.c, piAIOComm.c, piControlMain.c, piControlMain.h, piDIOComm.c, process_image.h, revpi_core.c, revpi_gate.c
The piControl kernel modules uses a global bool variable “piDev_g.stopIO” which can be set by means of ioctls to steer the input/output value processing: if the variable is set to “false” input and output are processed as usual, while a value of “true” results in changing of input/output values being supressed (i.e. not passed from/to userspace).
The problem is that the variable is not threadsafe. This means that if it is changed by a userspace process the set value may or may not be visible to the processor that is currently processing the input/output (loop). In the worst case this may result in setting of the variable having no effect.
So ensure the data integrity by using the threadsafe bitoperations provided by the kernel. For this turn the boolean value into a unsigned long and …
=> piControl: ensure setting I/O processing state is threadsafe

Makefile
ARCH and CROSSCOMPILE should either be declared by the user or the buildsystem. Mangling with them in the Makefile is likely to break things. See customer issue: https://github.com/RevolutionPi/piControl/issues/81
Also remove two obsolete statements (comments).
This has been successfully tested with our kernelbakery for arm and arm64 builds
=> Remove ARCH and CROSS_COMPILE from Makefile [REVPI-2894]

revpi_common.c
In the initial commit [1] that introduced support for the RevPi Connect SE, the LED A3 was mistakenly forgotten. Fix this by adding a third machine type entry 'REVPI_CONNECT_SE' in the if clause.
[1] 2fdd1f4adab8e3e095808704b71e3ae2b313da6e
=> Connect SE: Make led A3 usable via process image [REVPI-3091]

common_define.h, piTest/piTest.c
Besides the implementation of the Connect 4 support in piControl, we need to add the device as known in piTest.
=> piTest: Add Connect 4 as known device

piIOComm.h
REV_PI_TTY_DEVICE is no longer necessary since UART access has been changed to serdev.
=> Remove unused constat REV_PI_TTY_DEVICE

project.h
During the piBridge communication lots of messages are logged in the kernel log that indicate UART data reception errors like parity, frame and (occassionally) overflow errors.
As it turned out increasing the realtime priority of the thread that handles the piBridge communication to 54 (which is the same as the SPI thread priority) fixes these issues.
Before this change an error rate (ratio of total errors to received bytes) of 0,000812359 (i.e. 0,081%) could be observerd during a 45 minute test. After this change the error rate is decreased to 0 (i.e. no errors at all). This rate is even below the error rate that is observed with the 4.19 Revpi kernel (0,0000262%)
NOTE: The reason for this effect is still not completely clear, presumably the UART has to switch as quickly as possible from …
=>  piControl: increase priority of io-thread

project.h
During the piBridge communication lots of messages are logged in the kernel log that indicate UART data reception errors like parity, frame and (occassionally) overflow errors.
As it turned out increasing the realtime priority of the thread that handles the piBridge communication to 54 (which is the same as the SPI thread priority) fixes these issues.
Bevore this change an error rate (ratio of total errors to received bytes) of 0,000563221 (i.e. 0,056%) could be observerd during a 45 minute test. After this change the error rate is decreased to 0 (i.e. no errors at all). This rate is even below the error rate that is observed with the 4.19 Revpi kernel (0,0000262%)
NOTE: The reason for this effect is still not completely clear, presumably the UART has to switch as quickly as possible from …
=> piControl: increase priority of io-thread

README.md
Add a README file which describes the build process of the piControl module. This will ease the onboarding process for new developers and customers, who want to make changes or contribute to the upstream development.
=> Add README with basic build instructions

PiBridgeMaster.c
The signaling on the piBridge starts with the ACK pins (2A and 2B). The pins are driven high in output mode. The we are waiting 9 ms and the pins are configured to input mode. The signal is then pulled down by an external resistor to ground level.
On the Module side the transition from low to high is the beginning of the initialization sequence. After this the ACK pin must stay high for >= 7.5 ms and <= 9.5 ms. If the level drops earlier or later the module will go back to the start of the initialization sequence and it will wait for a low -> high transition on the ACK pin.
On the Connect 4 it happens that the transition from high to low takes longer. As the current levels are not dropping as fast as expected. In some cases it takes more then 0.5 ms. And as we wait 9 ms until we switch …
=> fix: Too long high pulse on the left ACK pin on Connect 4

PiBridgeMaster.c
The signaling on the piBridge starts with the ACK pins (2A and 2B). The pins are driven high in output mode. We are waiting 9 ms then the pins are configured to input mode. The signal is then pulled down by an external resistor to ground level.
On the Module side the transition from low to high is the beginning of the initialization sequence. After this the ACK pin must stay high for >= 7.5 ms and <= 9.5 ms. If the level drops earlier or later the module will go back to the start of the initialization sequence and it will wait for a low -> high transition on the ACK pin.
On the Connect 4 it happens that the transition from high to low takes longer. As the current levels are not dropping as fast as expected. In some cases it takes more then 0.5 ms. And as we wait 9 ms until we switch the …
=> fix: Too long high pulse on the left ACK pin on Connect 4 (revpi-6.1) [REVPI-3644]
